import '../models/transaction_model.dart';
import '../models/budget.dart';
import '../models/goal.dart';
import '../models/debt.dart';
import 'package:intl/intl.dart';

class DailyQuest {
  final String title;
  final String description;
  final int xpReward;
  final bool isCompleted;

  DailyQuest({
    required this.title,
    required this.description,
    required this.xpReward,
    required this.isCompleted,
  });
}

class Achievement {
  final String title;
  final String icon;
  final String description;
  final double currentProgress;
  final double targetProgress;
  final String unit;

  Achievement({
    required this.title,
    required this.icon,
    required this.description,
    required this.currentProgress,
    required this.targetProgress,
    this.unit = '',
  });

  bool get isUnlocked => currentProgress >= targetProgress;
  double get progressPercentage => (currentProgress / targetProgress).clamp(0.0, 1.0);
}

class GamificationProfile {
  final int xp;
  final int level;
  final int streakDays;
  final List<DailyQuest> dailyQuests;
  final List<Achievement> achievements;

  GamificationProfile({
    required this.xp,
    required this.level,
    required this.streakDays,
    required this.dailyQuests,
    required this.achievements,
  });

  double get progressToNextLevel => (xp % 500) / 500;
}

class GamificationService {
  static GamificationProfile generateProfile({
    required List<Transaction> transactions,
    required List<Budget> budgets,
    required List<Goal> goals,
    required List<Debt> debts,
  }) {
    // 1. Calculate Base XP
    int txXp = transactions.length * 10;
    int budgetXp = budgets.length * 50;
    
    int completedGoals = goals.where((g) => g.targetAmount > 0 && g.savedAmount >= g.targetAmount).length;
    int goalXp = completedGoals * 100;

    int completedDebts = debts.where((d) => d.totalAmount > 0 && d.paidAmount >= d.totalAmount).length;
    int debtXp = completedDebts * 50;

    final datesActive = transactions.map((t) => DateFormat('yyyy-MM-dd').format(t.date)).toSet();
    int activeDaysXp = datesActive.length * 20;

    int totalXp = txXp + budgetXp + goalXp + debtXp + activeDaysXp;
    if (totalXp == 0 && transactions.isEmpty) totalXp = 0;

    int level = (totalXp ~/ 500) + 1;

    // 2. Calculate Streak
    int streak = 0;
    DateTime today = DateTime.now();
    for (int i = 0; i < 365; i++) {
        DateTime d = today.subtract(Duration(days: i));
        String dStr = DateFormat('yyyy-MM-dd').format(d);
        if (datesActive.contains(dStr)) {
            streak++;
        } else {
            if (i == 0) continue; 
            break;
        }
    }

    // 3. Evaluate Daily Quests
    String todayStr = DateFormat('yyyy-MM-dd').format(today);
    bool loggedToday = datesActive.contains(todayStr);
    bool hasActiveBudget = budgets.any((b) => b.month == today.month && b.year == today.year);
    bool fundedGoalToday = transactions.any((t) => 
        DateFormat('yyyy-MM-dd').format(t.date) == todayStr && 
        t.goalKey != null && 
        t.type == TransactionType.expense); // Expense to wallet = funding a goal

    List<DailyQuest> quests = [
      DailyQuest(
        title: 'Daily Tracker',
        description: 'Record any transaction today.',
        xpReward: 20,
        isCompleted: loggedToday,
      ),
      DailyQuest(
        title: 'Future Planner',
        description: 'Have an active budget set for this month.',
        xpReward: 10,
        isCompleted: hasActiveBudget,
      ),
      DailyQuest(
        title: 'Wealth Builder',
        description: 'Add money to any savings goal today.',
        xpReward: 30,
        isCompleted: fundedGoalToday,
      ),
    ];

    // Add extra XP theoretically generated by quests today (just for the UI to feel responsive if they aren't derived elsewhere)
    if (hasActiveBudget) totalXp += 10;
    if (fundedGoalToday) totalXp += 30;
    // loggedToday is already covered natively by strictly adding activeDaysXp (which gives 20)

    level = (totalXp ~/ 500) + 1; // Recalculate level just in case

    // 4. Calculate Achievements
    final owedDebts = debts.where((d) => !d.isOwedToMe).toList();
    final double totalPaidDebt = owedDebts.fold(0.0, (sum, d) => sum + d.paidAmount);
    final double totalRemainingOwed = owedDebts.fold(0.0, (sum, d) => sum + (d.totalAmount - d.paidAmount).clamp(0.0, double.infinity));
    final double totalSaved = goals.fold(0.0, (sum, g) => sum + g.savedAmount);

    List<Achievement> achievementsList = [
      Achievement(
        title: 'Loyal Tracker',
        icon: '📝',
        description: 'Log 50 transactions to build a habit.',
        currentProgress: transactions.length.toDouble(),
        targetProgress: 50.0,
        unit: 'logs',
      ),
      Achievement(
        title: 'Wealth Accumulator',
        icon: '💰',
        description: 'Save ₱10,000 across your savings goals.',
        currentProgress: totalSaved,
        targetProgress: 10000.0,
        unit: '₱',
      ),
      Achievement(
        title: 'On Fire',
        icon: '🔥',
        description: 'Reach a 7-day transaction streak.',
        currentProgress: streak.toDouble(),
        targetProgress: 7.0,
        unit: 'days',
      ),
      Achievement(
        title: 'Debt Destroyer',
        icon: '🏆',
        description: 'Pay off ₱5,000 of borrowed money.',
        currentProgress: totalPaidDebt,
        targetProgress: 5000.0,
        unit: '₱',
      ),
      Achievement(
        title: 'Debt Free (Bonus)',
        icon: '👼',
        description: 'Have zero outstanding borrowed money.',
        currentProgress: totalRemainingOwed <= 0 && owedDebts.isNotEmpty ? 1.0 : 0.0,
        targetProgress: 1.0,
        unit: 'done',
      ),
    ];

    return GamificationProfile(
      xp: totalXp,
      level: level,
      streakDays: streak,
      dailyQuests: quests,
      achievements: achievementsList,
    );
  }
}
