import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:image/image.dart' as img;
import 'package:path_provider/path_provider.dart';

class MonthDumpService {
  static Future<File> generatePictureCollage(List<String> imagePaths, String title) async {
    final tempDir = await getTemporaryDirectory();
    final outputPath = '${tempDir.path}/dump_collage_${DateTime.now().millisecondsSinceEpoch}.jpg';
    
    // 1. Pick max 16 images
    final targetPaths = imagePaths.take(16).toList();
    final int cols = targetPaths.length > 9 ? 4 : (targetPaths.length > 4 ? 3 : 2);
    final int canvasSize = 1200;
    final int imgSize = (canvasSize - 120) ~/ cols;
    final int margin = 16;

    // 2. Process images in parallel
    // This is the major optimization: using multiple isolates to decode and resize simultaneously
    final List<Future<img.Image?>> processingTasks = targetPaths.map((path) {
      return compute(_processSingleImage, {
        'path': path,
        'size': imgSize - margin,
      });
    }).toList();

    final List<img.Image?> thumbnails = await Future.wait(processingTasks);

    // 3. Composite everything onto the final canvas
    final success = await compute(_compositeCollage, {
      'thumbnails': thumbnails,
      'outputPath': outputPath,
      'title': title,
      'canvasSize': canvasSize,
      'cols': cols,
      'imgSize': imgSize,
    });
    
    if (success) return File(outputPath);
    throw Exception('Failed to generate collage');
  }

  static Future<File> generateVideoSlideshow(List<String> imagePaths, String title) async {
    final tempDir = await getTemporaryDirectory();
    final outputPath = '${tempDir.path}/dump_slideshow_${DateTime.now().millisecondsSinceEpoch}.gif';
    
    // Process frames in parallel for the GIF as well
    final targetPaths = imagePaths.take(15).toList();
    
    final List<Future<img.Image?>> processingTasks = targetPaths.map((path) {
      return compute(_processSingleFrame, {
        'path': path,
        'title': title,
      });
    }).toList();

    final List<img.Image?> frames = await Future.wait(processingTasks);

    final success = await compute(_encodeGifIsolate, {
      'frames': frames.whereType<img.Image>().toList(),
      'outputPath': outputPath,
    });
    
    if (success) return File(outputPath);
    throw Exception('Failed to generate slideshow');
  }
}

/// Worker function to process a single image for the collage
img.Image? _processSingleImage(Map<String, dynamic> params) {
  try {
    final path = params['path'] as String;
    final size = params['size'] as int;
    
    final file = File(path);
    if (!file.existsSync()) return null;

    // Decode the image
    final decoded = img.decodeImage(file.readAsBytesSync());
    if (decoded == null) return null;

    // Center crop to square
    final sqSize = decoded.width < decoded.height ? decoded.width : decoded.height;
    final cropped = img.copyCrop(decoded, 
      x: (decoded.width - sqSize) ~/ 2, 
      y: (decoded.height - sqSize) ~/ 2, 
      width: sqSize, height: sqSize);
    
    // Resize using nearest interpolation for speed
    return img.copyResize(cropped, width: size, height: size, interpolation: img.Interpolation.nearest);
  } catch (e) {
    return null;
  }
}

/// Worker function to composite the final collage
bool _compositeCollage(Map<String, dynamic> params) {
  try {
    final thumbnails = params['thumbnails'] as List<img.Image?>;
    final outputPath = params['outputPath'] as String;
    final title = params['title'] as String;
    final canvasSize = params['canvasSize'] as int;
    final cols = params['cols'] as int;
    final imgSize = params['imgSize'] as int;

    final canvas = img.Image(width: canvasSize, height: canvasSize + 250);
    img.fill(canvas, color: img.ColorRgb8(15, 15, 20)); // Dark premium background
    
    // draw text
    img.drawString(canvas, title, font: img.arial48, x: 60, y: 80, color: img.ColorRgb8(255, 255, 255));
    img.drawString(canvas, 'Monthly attachment dump generated by RootEXP', font: img.arial24, x: 60, y: 150, color: img.ColorRgb8(150, 150, 150));

    for (int i = 0; i < thumbnails.length; i++) {
      final thumb = thumbnails[i];
      if (thumb == null) continue;

      final row = i ~/ cols;
      final col = i % cols;
      final x = 60 + col * imgSize;
      final y = 220 + row * imgSize;

      img.compositeImage(canvas, thumb, dstX: x, dstY: y);
    }

    final jpgBytes = img.encodeJpg(canvas, quality: 85); // 85 is usually plenty and faster to encode
    File(outputPath).writeAsBytesSync(jpgBytes);
    return true;
  } catch (e) {
    return false;
  }
}

/// Worker function to process a single frame for the GIF
img.Image? _processSingleFrame(Map<String, dynamic> params) {
  try {
    final path = params['path'] as String;
    final title = params['title'] as String;
    
    final file = File(path);
    if (!file.existsSync()) return null;

    final decoded = img.decodeImage(file.readAsBytesSync());
    if (decoded == null) return null;

    // Crop to 4:5 aspect ratio
    final aspect = 4 / 5;
    int cropWidth = decoded.width;
    int cropHeight = (decoded.width / aspect).round();
    if (cropHeight > decoded.height) {
      cropHeight = decoded.height;
      cropWidth = (decoded.height * aspect).round();
    }

    final cropped = img.copyCrop(decoded, 
      x: (decoded.width - cropWidth) ~/ 2, 
      y: (decoded.height - cropHeight) ~/ 2, 
      width: cropWidth, height: cropHeight);
    
    final resized = img.copyResize(cropped, width: 600, height: 750, interpolation: img.Interpolation.nearest);
    
    // Draw text overlay
    img.fillRect(resized, x1: 0, y1: 650, x2: 600, y2: 750, color: img.ColorRgba8(0, 0, 0, 150));
    img.drawString(resized, title, font: img.arial48, x: 40, y: 670, color: img.ColorRgb8(255, 255, 255));

    return resized;
  } catch (e) {
    return null;
  }
}

/// Worker function to encode the GIF
bool _encodeGifIsolate(Map<String, dynamic> params) {
  try {
    final frames = params['frames'] as List<img.Image>;
    final outputPath = params['outputPath'] as String;

    if (frames.isEmpty) return false;

    img.Image? animation;
    for (final frame in frames) {
      if (animation == null) {
        animation = frame;
      } else {
        animation.addFrame(frame);
      }
    }

    if (animation == null) return false;

    for (final frame in animation.frames) {
      frame.frameDuration = 800;
    }

    final gifBytes = img.encodeGif(animation);
    File(outputPath).writeAsBytesSync(gifBytes);
    return true;
  } catch (e) {
    return false;
  }
}
