import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:image/image.dart' as img;
import 'package:path_provider/path_provider.dart';

class MonthDumpService {
  static Future<File> generatePictureCollage(List<String> imagePaths, String title) async {
    final tempDir = await getTemporaryDirectory();
    final outputPath = '${tempDir.path}/dump_collage_${DateTime.now().millisecondsSinceEpoch}.jpg';
    
    final success = await compute(_generateCollageIsolate, {
      'paths': imagePaths,
      'outputPath': outputPath,
      'title': title,
    });
    
    if (success) return File(outputPath);
    throw Exception('Failed to generate collage');
  }

  static Future<File> generateVideoSlideshow(List<String> imagePaths, String title) async {
    final tempDir = await getTemporaryDirectory();
    final outputPath = '${tempDir.path}/dump_slideshow_${DateTime.now().millisecondsSinceEpoch}.gif';
    
    final success = await compute(_generateGifIsolate, {
      'paths': imagePaths,
      'outputPath': outputPath,
      'title': title,
    });
    
    if (success) return File(outputPath);
    throw Exception('Failed to generate slideshow');
  }
}

bool _generateCollageIsolate(Map<String, dynamic> params) {
  try {
    final paths = params['paths'] as List<String>;
    final outputPath = params['outputPath'] as String;
    final title = params['title'] as String;

    // Pick max 16 images for a 4x4 or 9 for a 3x3
    final targetPaths = paths.take(16).toList();
    
    final int canvasSize = 1200;
    final canvas = img.Image(width: canvasSize, height: canvasSize + 250);
    
    // fill background
    img.fill(canvas, color: img.ColorRgb8(15, 15, 20)); // Dark premium background
    
    // draw text "title"
    img.drawString(canvas, title, font: img.arial48, x: 60, y: 80, color: img.ColorRgb8(255, 255, 255));
    img.drawString(canvas, 'Monthly attachment dump generated by RootEXP', font: img.arial24, x: 60, y: 150, color: img.ColorRgb8(150, 150, 150));

    // Draw grid
    final int cols = targetPaths.length > 9 ? 4 : (targetPaths.length > 4 ? 3 : 2);
    final int imgSize = (canvasSize - 120) ~/ cols;
    int margin = 16;

    for (int i = 0; i < targetPaths.length; i++) {
      final imgFile = File(targetPaths[i]);
      if (!imgFile.existsSync()) continue;

      final decoded = img.decodeImage(imgFile.readAsBytesSync());
      if (decoded == null) continue;

      // Center crop to square
      final sqSize = decoded.width < decoded.height ? decoded.width : decoded.height;
      final cropped = img.copyCrop(decoded, 
        x: (decoded.width - sqSize) ~/ 2, 
        y: (decoded.height - sqSize) ~/ 2, 
        width: sqSize, height: sqSize);
      
      final resized = img.copyResize(cropped, width: imgSize - margin, height: imgSize - margin);

      final row = i ~/ cols;
      final col = i % cols;
      final x = 60 + col * imgSize;
      final y = 220 + row * imgSize;

      img.compositeImage(canvas, resized, dstX: x, dstY: y);
    }

    final jpgBytes = img.encodeJpg(canvas, quality: 90);
    File(outputPath).writeAsBytesSync(jpgBytes);
    return true;
  } catch (e) {
    debugPrint('Collage error: $e');
    return false;
  }
}

bool _generateGifIsolate(Map<String, dynamic> params) {
  try {
    final paths = params['paths'] as List<String>;
    final outputPath = params['outputPath'] as String;
    final title = params['title'] as String;

    // Limit to 15 frames for memory and file size constraints
    final targetPaths = paths.take(15).toList();

    // Create a multi-frame image for GIF
    // In image package v4, we can just create the first frame and add more frames to it
    img.Image? animation;
    
    for (int i = 0; i < targetPaths.length; i++) {
      final imgFile = File(targetPaths[i]);
      if (!imgFile.existsSync()) continue;

      final decoded = img.decodeImage(imgFile.readAsBytesSync());
      if (decoded == null) continue;

      // Crop to 4:5 aspect ratio
      final aspect = 4 / 5;
      int cropWidth = decoded.width;
      int cropHeight = (decoded.width / aspect).round();
      if (cropHeight > decoded.height) {
        cropHeight = decoded.height;
        cropWidth = (decoded.height * aspect).round();
      }

      final cropped = img.copyCrop(decoded, 
        x: (decoded.width - cropWidth) ~/ 2, 
        y: (decoded.height - cropHeight) ~/ 2, 
        width: cropWidth, height: cropHeight);
      
      final resized = img.copyResize(cropped, width: 800, height: 1000);
      
      // Draw text overlay on every frame
      img.fillRect(resized, x1: 0, y1: 850, x2: 800, y2: 1000, color: img.ColorRgba8(0, 0, 0, 150));
      img.drawString(resized, title, font: img.arial48, x: 40, y: 880, color: img.ColorRgb8(255, 255, 255));
      img.drawString(resized, 'RootEXP Dump', font: img.arial24, x: 40, y: 940, color: img.ColorRgb8(200, 200, 200));

      if (animation == null) {
        animation = resized;
      } else {
        animation.addFrame(resized);
      }
    }

    if (animation == null) return false;

    // Set duration for each frame
    for (final frame in animation.frames) {
      frame.frameDuration = 800; // 800ms per frame
    }

    final gifBytes = img.encodeGif(animation);
    File(outputPath).writeAsBytesSync(gifBytes);
    return true;
  } catch (e) {
    debugPrint('GIF error: $e');
    return false;
  }
}
